version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/testing-codedeploy
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu

  ValidateService:
    - location: scripts/validate.sh
      runas: ubuntu
